version: "3"

services:
  predict_app:
    build:
      context: ./app
      dockerfile: Dockerfile.predict_dev
    image: mlops-app
    container_name: mlops-app
    ports:
      - "5050:5050"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=docker_db
      - MYSQL_USER=docker_user
      - MYSQL_PASSWORD=docker_pass
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./app:/app

  db:
    image: mysql:5.7
    container_name: mlops-db
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: docker_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_pass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  
  notebook:
    build:
      context: ./app
      dockerfile: Dockerfile.notebook
    container_name: mlops-notebook
    ports:
      - "8887:8888"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=docker_db
      - MYSQL_USER=docker_user
      - MYSQL_PASSWORD=docker_pass
      - JUPYTER_ENABLE_LAB=yes
    links:
      - db
    volumes:
      - ./app/ml:/home/jovyan/work