version: "3"

services:
  predict_app:
    build:
      context: .
      dockerfile: Dockerfile.predict_dev
    image: mlops-app
    container_name: mlops-app
    ports:
      - "5050:5050"
    environment:
      - PG_HOST=db
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres12345
      - PG_DATABASE=mlops_db
      - PG_HOST_PRD=ec2-54-236-156-167.compute-1.amazonaws.com
      - PG_PORT_PRD=5432
      - PG_USER_PRD=qejymygxyhmqox
      - PG_PASSWORD_PRD="${PG_PASSWORD_PRD}"
      - PG_DATABASE_PRD=deogivl4vrki52
    links:
      - db
    volumes:
      - ./app:/app
      - ./ml/resources/deploy:/app/deploy
      - ./ml/utils:/app/utils

  db:
    image: mysql:5.7
    container_name: mlops-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    container_name: mlops-notebook
    ports:
      - "8887:8888"
    environment:
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres12345
      - PG_DATABASE=mlops_db
      - MYSQL_DATABASE=test_database
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - JUPYTER_ENABLE_LAB=yes
    links:
      - db
    volumes:
      - ./ml:/work