FROM python:3.9.1

WORKDIR /app

COPY ./app /app

RUN pip install --upgrade pip && pip install \
  Flask \
  numpy \
  pandas \
  scikit-learn \
  psycopg2 \
  sqlalchemy

EXPOSE 50
CMD ["python3", "index.py"]