version: "3"

services:
  predict_app:
    build:
      context: .
      dockerfile: Dockerfile.predict_dev
    image: mlops-app
    container_name: mlops-app
    ports:
      - "5050:5050"
    environment:
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres12345
      - PG_DATABASE=mlops_db
      - PG_PORT_PRD=5432
      - PG_USER_PRD=postgres
      - PG_PASSWORD_PRD=postgres12345
      - PG_DATABASE_PRD=mlops_db
    links:
      - db
    volumes:
      - ./app:/app
      - ./ml/resources/deploy:/app/deploy
      - ./ml/utils:/app/utils

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: mlops-db
    container_name: mlops-db
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres12345
      - PGPASSWORD=postgres12345
      - POSTGRES_DB=mlops_db
      - DATABASE_HOST=localhost
    volumes:
      - ./db:/db
      - ./db/init:/docker-entrypoint-initdb.d
  
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    image: mlops-notebook
    container_name: mlops-notebook
    ports:
      - "8887:8888"
    environment:
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres12345
      - PG_DATABASE=mlops_db
      - JUPYTER_ENABLE_LAB=yes
    links:
      - db
    volumes:
      - ./ml:/work