FROM jupyter/datascience-notebook
USER root
ENV DEBCONF_NOWARNINGS yeso
RUN apt-get update
RUN apt-get install -y libpq-dev
USER jovyan
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install --no-cache-dir \
    imblearn==0.0 \
    ipython-sql==0.3.9 \
    PyMySQL==1.0.2 \
    gokart==1.0.7 

