FROM python:3.7.4

RUN curl -O https://chromedriver.storage.googleapis.com/77.0.3865.40/chromedriver_linux64.zip && unzip chromedriver_linux64.zip -d ~/bin/

WORKDIR /app

RUN pip install --upgrade pip && pip install \
  dash==2.0.0 \
  numpy==1.17.2 \
  pandas==0.25.1 \
  scikit-learn==0.21.3 \
  PyMySQL==1.0.2 \
  sqlalchemy==1.4.29 \
  boto3==1.20.54

ENV APP_ENV dev
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8

EXPOSE 5050
CMD ["python", "app.py"]