name: CICD
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  PG_PASSWORD_PRD: ${{ secrets.PG_PASSWORD_PRD }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to Heroku.
        uses: jctaveras/heroku-deploy@v1.0.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: ./Dockerfile.predict_prd
          docker_options: "--no-cache"