name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Container
        run: docker-compose up -d --build
      - name: Run a flask test script
        run: docker-compose exec -T predict_app python3 test.py
